pipeline {
  agent any

  stages {
      stage('Build Artifact') {
            steps {
              sh '''
              cd SecOps
              mvn clean package -DskipTests=true '''
              
            }
        }   
      stage('test and jacoco report') {
            steps {
              sh '''
              
              mvn test'''
              
            }
post{
always{
junit 'target/surefire-reports/*.xml'
jacoco execPattern: 'target/jacoco.exec'
}}
        }
    }

}
