pipeline {
  agent any

  stages {
      stage('Build Artifact') {
            steps {
              sh '''
              cd SecOps
              mvn clean package -DskipTests=true '''
              
            }
        }   
    }
}