pipeline {
  agent any

  stages {
      stage('Build Artifact') {
            steps {
              sh '''
              cd SecOps
              mvn clean package -DskipTests=true '''
              
            }
        }   
    }
     post {
        success {
            jacoco(
                execPattern: '**/build/jacoco/*.exec',
                classPattern: '**/build/classes/java/main',
                sourcePattern: '**/src/main'
            )
        }
    }
}
