pipeline{
    agent any
    stages{
        stage('first stage'){
            steps{
                sh '''
                    echo Hello from the first stage 
                '''
            }
        }
           stage('second stage'){
            steps{
                sh '''
                    echo Hello from the second stage 
                '''
            }
        }
    }
}