/*@Library('roboshop') _
*/

pipeline{
    agent any
    stages{
        stage('git version'){
            steps{
                sh '''
                    git version 
                '''
            }
        }
        stage('second stage'){
        steps{
            sh '''
                mvn -v 
            '''
        }
        }

        stage('docker'){
        steps{
            sh '''
                docker version
            '''
        }}
         stage('k8s cli '){
        steps{
            sh '''
                kubectl version --short
            '''
        }}



   
        }
    }


