pipeline {
    agent any
    
    stages {
    
        stage('Scan with Trivy') {
            steps {
                script {
                    // Install Trivy
                    sh '''
                        trivy --version
                        trivy image --severity HIGH,CRITICAL nginx:1.24.0-alpine
                       

                    
                    '''

                }
            }
        }
    }
    

}
