pipeline {
    agent any
    
    stages {
    
        stage('Scan with Trivy') {
            steps {
                script {
                    // Install Trivy
                    sh '''
                        trivy --version
                        trivy image -f json -o results.json --vuln-type os --severity HIGH,CRITICAL centos:7
                        cat results.json
                       

                    
                    '''

                }
            }
        }
    }
    

}
